# Core services, they are not Symfony-dependent
services:

    # Default in-memory storage, to be used as an in-memory cache in order to
    # avoid running the node collect events too many times
    php_acl.store.memory:
        public: false
        class: MakinaCorpus\ACL\Store\MemoryEntryStore
        tags: [{name: php_acl.entry_store}]

    php_acl.permission_map:
        public: true
        alias: php_acl.permission_map.default

    php_acl.permission_map.default:
        public: false
        class: MakinaCorpus\ACL\PermissionMap

    # All arguments for this class will be set using a compilation pass
    php_acl.manager:
        public: true
        class: MakinaCorpus\ACL\Manager

    # ACL voter for Symfony security component
    php_acl.voter:
        public: false
        class: MakinaCorpus\ACL\Bridge\Symfony\ACLVoter
