services:

    # Collect profiles from Drupal user accounts
    php_acl.drupal.profile_collector:
        public: false
        class: MakinaCorpus\ACL\Bridge\Drupal\UserGrantProfileCollector
        tags: [{name: php_acl.profile_collector}]

    # Converts entities to ('entity_type', 'entity_id') resources
    php_acl.drupal.resource_converter:
        public: false
        class: MakinaCorpus\ACL\Bridge\Drupal\EntityResourceConverter
        tags: [{name: php_acl.resource_converter}]

    # Component that converts entry lists for nodes to Drupal node
    # access API, will be used by the sf_acl module
    php_acl.drupal.entry_to_node_access_converter:
        public: true
        class: MakinaCorpus\ACL\Bridge\Drupal\EntryToNodeAccessConverter

    # This service will be manually used within the module hooks to convert
    # acl as Drupal node access records information
    # @todo
